vim.api.nvim_set_hl(0, "htmlEndTag", { link = "Function" })
vim.api.nvim_set_hl(0, "@keyword.function", { link = "@keyword" })
vim.api.nvim_set_hl(0, "PreProc", { link = "@keyword" })
vim.api.nvim_set_hl(0, "Function", { fg = "#ff4586" })
vim.api.nvim_set_hl(0, "@lsp.typemod.method.defaultLibrary.vue", { link = "Function" })
vim.api.nvim_set_hl(0, "@lsp.typemod.class.defaultLibrary.vue", { link = "Function" })
vim.api.nvim_set_hl(0, "@lsp.typemod.function.defaultLibrary.vue", { link = "Function" })
vim.api.nvim_set_hl(0, "@lsp.type.class.vue", { link = "Function" })
vim.api.nvim_set_hl(0, "@variable.builtin", { link = "Type" })
vim.api.nvim_set_hl(0, "@keyword.operator.typescript", { link = "@keyword" })

vim.api.nvim_set_hl(0, "DapUIPlayPause", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIStepInto", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIStepOver", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIStepOut", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIStepBack", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIRestart", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIStop", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIPlayPauseNC", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIStepIntoNC", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIStepOverNC", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIStepOutNC", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIStepBackNC", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIRestartNC", { link = "@property" })
vim.api.nvim_set_hl(0, "DapUIStopNC", { link = "@property" })

vim.api.nvim_set_hl(0, "@tag.builtin.tsx", { link = "Statement" })
vim.api.nvim_set_hl(0, "@tag.delimiter.tsx", { link = "Special" })
