return {
  -- "hrsh7th/nvim-cmp",
  -- dependencies = {
  --   "L3MON4D3/LuaSnip",
  --   "hrsh7th/cmp-nvim-lsp",
  --   "hrsh7th/cmp-buffer",
  --   "hrsh7th/cmp-path",
  -- },
  -- config = function()
  --   local cmp = require("cmp")
  --   local luasnip = require("luasnip")
  --
  --   cmp.setup({
  --     snippet = {
  --       expand = function(args)
  --         luasnip.lsp_expand(args.body)
  --       end,
  --     },
  --
  --     mapping = cmp.mapping.preset.insert({
  --       ["<C-Space>"] = cmp.mapping.complete(),
  --       ["<Tab>"] = cmp.mapping.confirm({ select = true }),
  --       ["<C-n>"] = cmp.mapping.select_next_item(),
  --       ["<C-p>"] = cmp.mapping.select_prev_item(),
  --       ["<C-d>"] = cmp.mapping.scroll_docs(-4),
  --       ["<C-f>"] = cmp.mapping.scroll_docs(4),
  --     }),
  --
  --     sources = cmp.config.sources({
  --       { name = "nvim_lsp" },
  --       { name = "luasnip" },
  --       { name = "buffer" },
  --       { name = "path" },
  --     }),
  --
  --     window = {
  --       completion = cmp.config.window.bordered(),
  --       documentation = cmp.config.window.bordered(),
  --     },
  --   })
  -- end,
}
